"""create concepts, mastery, questions, question_attempts, misconceptions

Revision ID: 4d2bbe285525
Revises: 2b5ec1fb0386
Create Date: 2026-09-14 17:24:19.722978

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4d2bbe285525'
down_revision: Union[str, Sequence[str], None] = '2b5ec1fb0386'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('concepts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('knowledge_space_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['knowledge_space_id'], ['knowledge_spaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_concepts_knowledge_space_id'), 'concepts', ['knowledge_space_id'], unique=False)
    op.create_table('mastery',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('concept_id', sa.Integer(), nullable=False),
    sa.Column('fsrs_state', sa.Integer(), nullable=False),
    sa.Column('fsrs_step', sa.Integer(), nullable=True),
    sa.Column('fsrs_stability', sa.Float(), nullable=True),
    sa.Column('fsrs_difficulty', sa.Float(), nullable=True),
    sa.Column('fsrs_due', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fsrs_last_review', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('correct', sa.Integer(), nullable=False),
    sa.Column('incorrect', sa.Integer(), nullable=False),
    sa.Column('last_correct_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_incorrect_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'concept_id', name='uq_mastery_user_concept')
    )
    op.create_index(op.f('ix_mastery_concept_id'), 'mastery', ['concept_id'], unique=False)
    op.create_index(op.f('ix_mastery_user_id'), 'mastery', ['user_id'], unique=False)
    op.create_table('misconceptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('concept_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_misconceptions_concept_id'), 'misconceptions', ['concept_id'], unique=False)
    op.create_index(op.f('ix_misconceptions_user_id'), 'misconceptions', ['user_id'], unique=False)
    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('concept_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('correct_answer', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tolerance', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_questions_concept_id'), 'questions', ['concept_id'], unique=False)
    op.create_table('question_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('submitted_answer', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('evaluated_by', sa.String(length=20), nullable=False),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_question_attempts_question_id'), 'question_attempts', ['question_id'], unique=False)
    op.create_index(op.f('ix_question_attempts_user_id'), 'question_attempts', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_question_attempts_user_id'), table_name='question_attempts')
    op.drop_index(op.f('ix_question_attempts_question_id'), table_name='question_attempts')
    op.drop_table('question_attempts')
    op.drop_index(op.f('ix_questions_concept_id'), table_name='questions')
    op.drop_table('questions')
    op.drop_index(op.f('ix_misconceptions_user_id'), table_name='misconceptions')
    op.drop_index(op.f('ix_misconceptions_concept_id'), table_name='misconceptions')
    op.drop_table('misconceptions')
    op.drop_index(op.f('ix_mastery_user_id'), table_name='mastery')
    op.drop_index(op.f('ix_mastery_concept_id'), table_name='mastery')
    op.drop_table('mastery')
    op.drop_index(op.f('ix_concepts_knowledge_space_id'), table_name='concepts')
    op.drop_table('concepts')
    # ### end Alembic commands ###
