"""create concept_relationships

Revision ID: 56d25fd3f82d
Revises: cf741929a9c8
Create Date: 2026-09-14 18:19:50.477010

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56d25fd3f82d'
down_revision: Union[str, Sequence[str], None] = 'cf741929a9c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('concept_relationships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_concept_id', sa.Integer(), nullable=False),
    sa.Column('to_concept_id', sa.Integer(), nullable=False),
    sa.Column('relationship_type', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('from_concept_id != to_concept_id', name=op.f('ck_concept_relationships_ck_concept_relationship_no_self_edge')),
    sa.ForeignKeyConstraint(['from_concept_id'], ['concepts.id'], name=op.f('fk_concept_relationships_from_concept_id_concepts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_concept_id'], ['concepts.id'], name=op.f('fk_concept_relationships_to_concept_id_concepts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_concept_relationships')),
    sa.UniqueConstraint('from_concept_id', 'to_concept_id', 'relationship_type', name='uq_concept_relationship')
    )
    op.create_index(op.f('ix_concept_relationships_from_concept_id'), 'concept_relationships', ['from_concept_id'], unique=False)
    op.create_index(op.f('ix_concept_relationships_to_concept_id'), 'concept_relationships', ['to_concept_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_concept_relationships_to_concept_id'), table_name='concept_relationships')
    op.drop_index(op.f('ix_concept_relationships_from_concept_id'), table_name='concept_relationships')
    op.drop_table('concept_relationships')
    # ### end Alembic commands ###
