"""create personality_profiles

Revision ID: 6a2fab90b834
Revises: 53ad2c336601
Create Date: 2026-09-14 18:37:04.865768

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a2fab90b834'
down_revision: Union[str, Sequence[str], None] = '53ad2c336601'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('personality_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tone', sa.String(length=20), nullable=False),
    sa.Column('formality', sa.String(length=20), nullable=False),
    sa.Column('humor', sa.Float(), nullable=False),
    sa.Column('encouragement', sa.Float(), nullable=False),
    sa.Column('directness', sa.Float(), nullable=False),
    sa.Column('challenge_level', sa.Float(), nullable=False),
    sa.Column('verbosity', sa.String(length=20), nullable=False),
    sa.Column('teaching_style', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_personality_profiles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_personality_profiles'))
    )
    op.create_index(op.f('ix_personality_profiles_user_id'), 'personality_profiles', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_personality_profiles_user_id'), table_name='personality_profiles')
    op.drop_table('personality_profiles')
    # ### end Alembic commands ###
