"""add student profile fields to users

Revision ID: 6f513506fcef
Revises: 6a2fab90b834
Create Date: 2026-09-14 20:34:30.215212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f513506fcef'
down_revision: Union[str, Sequence[str], None] = '6a2fab90b834'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('education_level', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('course', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('institution', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('preferred_language', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('daily_study_target_minutes', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'daily_study_target_minutes')
    op.drop_column('users', 'preferred_language')
    op.drop_column('users', 'institution')
    op.drop_column('users', 'course')
    op.drop_column('users', 'education_level')
    # ### end Alembic commands ###
