"""add ON DELETE CASCADE to all domain foreign keys

Revision ID: b5ee5d199c84
Revises: 4d2bbe285525
Create Date: 2026-09-14 17:26:43.272317

Hand-adjusted after autogenerate: the raw autogenerated version rendered
`create_foreign_key(None, ...)` for every new constraint (fine for
upgrade(), but leaves downgrade() unable to reference them, since a name
of None can't identify a specific constraint to drop). Given explicit
names here matching server/db/base.py's new naming_convention, so both
directions actually run — see that file's docstring for why the
convention was added.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5ee5d199c84'
down_revision: Union[str, Sequence[str], None] = '4d2bbe285525'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# (table, column, referred_table, old_implicit_name, new_named_convention_name)
_FKS = [
    ("concepts", "knowledge_space_id", "knowledge_spaces",
     "concepts_knowledge_space_id_fkey", "fk_concepts_knowledge_space_id_knowledge_spaces"),
    ("generated_artifacts", "knowledge_space_id", "knowledge_spaces",
     "generated_artifacts_knowledge_space_id_fkey", "fk_generated_artifacts_knowledge_space_id_knowledge_spaces"),
    ("knowledge_spaces", "user_id", "users",
     "knowledge_spaces_user_id_fkey", "fk_knowledge_spaces_user_id_users"),
    ("knowledge_spaces", "parent_id", "knowledge_spaces",
     "knowledge_spaces_parent_id_fkey", "fk_knowledge_spaces_parent_id_knowledge_spaces"),
    ("mastery", "concept_id", "concepts",
     "mastery_concept_id_fkey", "fk_mastery_concept_id_concepts"),
    ("mastery", "user_id", "users",
     "mastery_user_id_fkey", "fk_mastery_user_id_users"),
    ("materials", "knowledge_space_id", "knowledge_spaces",
     "materials_knowledge_space_id_fkey", "fk_materials_knowledge_space_id_knowledge_spaces"),
    ("misconceptions", "concept_id", "concepts",
     "misconceptions_concept_id_fkey", "fk_misconceptions_concept_id_concepts"),
    ("misconceptions", "user_id", "users",
     "misconceptions_user_id_fkey", "fk_misconceptions_user_id_users"),
    ("question_attempts", "user_id", "users",
     "question_attempts_user_id_fkey", "fk_question_attempts_user_id_users"),
    ("question_attempts", "question_id", "questions",
     "question_attempts_question_id_fkey", "fk_question_attempts_question_id_questions"),
    ("questions", "concept_id", "concepts",
     "questions_concept_id_fkey", "fk_questions_concept_id_concepts"),
]


def upgrade() -> None:
    for table, column, referred_table, old_name, new_name in _FKS:
        op.drop_constraint(old_name, table, type_='foreignkey')
        op.create_foreign_key(new_name, table, referred_table, [column], ['id'], ondelete='CASCADE')


def downgrade() -> None:
    for table, column, referred_table, old_name, new_name in _FKS:
        op.drop_constraint(new_name, table, type_='foreignkey')
        op.create_foreign_key(old_name, table, referred_table, [column], ['id'])
