"""add flashcards table

Revision ID: eb49e809ebc5
Revises: 6f513506fcef
Create Date: 2026-09-16 20:41:39.383212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb49e809ebc5'
down_revision: Union[str, Sequence[str], None] = '6f513506fcef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flashcards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('knowledge_space_id', sa.Integer(), nullable=False),
    sa.Column('concept_id', sa.Integer(), nullable=True),
    sa.Column('front', sa.Text(), nullable=False),
    sa.Column('back', sa.Text(), nullable=False),
    sa.Column('fsrs_state', sa.Integer(), nullable=False),
    sa.Column('fsrs_step', sa.Integer(), nullable=True),
    sa.Column('fsrs_stability', sa.Float(), nullable=True),
    sa.Column('fsrs_difficulty', sa.Float(), nullable=True),
    sa.Column('fsrs_due', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fsrs_last_review', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviews', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], name=op.f('fk_flashcards_concept_id_concepts'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['knowledge_space_id'], ['knowledge_spaces.id'], name=op.f('fk_flashcards_knowledge_space_id_knowledge_spaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_flashcards'))
    )
    op.create_index(op.f('ix_flashcards_concept_id'), 'flashcards', ['concept_id'], unique=False)
    op.create_index(op.f('ix_flashcards_knowledge_space_id'), 'flashcards', ['knowledge_space_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_flashcards_knowledge_space_id'), table_name='flashcards')
    op.drop_index(op.f('ix_flashcards_concept_id'), table_name='flashcards')
    op.drop_table('flashcards')
    # ### end Alembic commands ###
