"""
One-off script: copies existing rows from server/users.db (SQLite —
`users`, `projects`, `generated_artifacts`) into PostgreSQL, so local dev
accounts created before the 2026-09-14 Postgres migration aren't silently
lost. Not part of the app's runtime path — run manually, once, per
environment that has an old users.db to migrate:

    python -m server.scripts.migrate_sqlite_to_postgres

Preserves original primary keys (so any external references stay valid),
then resets each table's identity sequence to MAX(id)+1 so future inserts
don't collide with migrated rows. Safe to re-run: existing rows (matched
by primary key) are skipped, not duplicated.
"""
from __future__ import annotations

import asyncio
import sqlite3
from pathlib import Path

from sqlalchemy import text

from ..db.session import async_session
from ..domains.identity.models import User
from ..domains.knowledge.models import GeneratedArtifact, KnowledgeSpace

_SQLITE_PATH = Path(__file__).resolve().parent.parent / "users.db"


async def main() -> None:
    if not _SQLITE_PATH.exists():
        print(f"no {_SQLITE_PATH} found — nothing to migrate.")
        return

    conn = sqlite3.connect(_SQLITE_PATH)
    conn.row_factory = sqlite3.Row
    try:
        user_rows = conn.execute("SELECT * FROM users").fetchall()
        project_rows = conn.execute("SELECT * FROM projects").fetchall()
        artifact_rows = conn.execute("SELECT * FROM generated_artifacts").fetchall()
    finally:
        conn.close()

    async with async_session() as db:
        migrated_users = 0
        for row in user_rows:
            existing = await db.get(User, row["id"])
            if existing is not None:
                continue
            db.add(
                User(
                    id=row["id"],
                    email=row["email"],
                    password_hash=row["password_hash"],
                    display_name=row["display_name"],
                    encryption_key=row["encryption_key"],
                )
            )
            migrated_users += 1
        await db.flush()

        # project id (sqlite) -> slug, so generated_artifacts (which
        # references project_slug, not project id) can find the matching
        # new KnowledgeSpace by (user_id, slug).
        slug_by_old_project_id: dict[int, str] = {}
        migrated_spaces = 0
        for row in project_rows:
            slug_by_old_project_id[row["id"]] = row["slug"]
            existing = await db.get(KnowledgeSpace, row["id"])
            if existing is not None:
                continue
            db.add(
                KnowledgeSpace(
                    id=row["id"],
                    user_id=row["user_id"],
                    slug=row["slug"],
                    display_name=row["display_name"],
                )
            )
            migrated_spaces += 1
        await db.flush()

        migrated_artifacts = 0
        for row in artifact_rows:
            existing = await db.get(GeneratedArtifact, row["id"])
            if existing is not None:
                continue
            slug = slug_by_old_project_id.get(row["project_slug"]) or row["project_slug"]
            space = await db.scalar(
                text(
                    "SELECT id FROM knowledge_spaces WHERE user_id = :uid AND slug = :slug"
                ),
                {"uid": row["user_id"], "slug": slug},
            )
            if space is None:
                print(f"  skipping artifact {row['id']!r}: no matching knowledge space for slug {slug!r}")
                continue
            db.add(
                GeneratedArtifact(
                    id=row["id"],
                    knowledge_space_id=space,
                    doc_type=row["doc_type"],
                    title=row["title"],
                    url_path=row["url_path"],
                )
            )
            migrated_artifacts += 1

        await db.commit()

        # Postgres identity columns default to GENERATED BY DEFAULT, which
        # allows explicit-value inserts (used above) but doesn't advance
        # the sequence — reset it so the next auto-generated insert doesn't
        # collide with a migrated id.
        for table, seq_col in (("users", "id"), ("knowledge_spaces", "id"), ("generated_artifacts", "id")):
            await db.execute(
                text(
                    f"SELECT setval(pg_get_serial_sequence('{table}', '{seq_col}'), "
                    f"COALESCE((SELECT MAX({seq_col}) FROM {table}), 1))"
                )
            )
        await db.commit()

    print(
        f"migrated {migrated_users} user(s), {migrated_spaces} knowledge space(s), "
        f"{migrated_artifacts} generated artifact(s)."
    )


if __name__ == "__main__":
    asyncio.run(main())
